version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: Pass123
      MARIADB_DATABASE: Pos_System
      MARIADB_USER: root
      MARIADB_PASSWORD: Pass123
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
