version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: pos-db
      MARIADB_USER: user
      MARIADB_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
